---
# This playbook will install MariaDB and start Mysql service.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  changed_when: False

- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Open port {{ mysql_port }} on firewalld if LAMP not on same host
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  when: lamp_on_same_host|default(false)|bool == false

- name: Close port {{ mysql_port }} on firewalld if LAMP on same host
  firewalld: port={{ mysql_port }}/tcp permanent=true state=disabled immediate=yes
  when: lamp_on_same_host|default(false)|bool == true
